"""create tables

Revision ID: 9bf28c243759
Revises: 
Create Date: 2022-09-24 01:12:33.673314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bf28c243759'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_id',
    sa.Column('job_id', sa.String(length=512), nullable=False),
    sa.Column('tweet_id', sa.String(length=512), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_id')
    # ### end Alembic commands ###
